name: Terraform Validation

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  terraform-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Init and Validate Day1
        working-directory: ./day1
        run: |
          terraform init
          terraform validate
          terraform plan

      - name: Init and Validate Day2
        working-directory: ./day2
        run: |
          terraform init
          terraform validate
          terraform plan -var-file="dev.tfvars"

      - name: Init and Validate Day3
        working-directory: ./day3
        run: |
          terraform init
          terraform validate
          terraform plan

      - name: Init and Validate Day4
        working-directory: ./day4
        run: |
          terraform init
          terraform validate
          terraform plan
